# Generated by Django 6.0.3 on 2026-04-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('date_of_planting', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('seedlings_planted', models.IntegerField(default=0)),
                ('species_planted', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('survived', models.IntegerField(default=0, help_text='Number of trees that survived')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('hectares', models.FloatField(default=0, help_text='Area covered in hectares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_plantings', to='api.county')),
            ],
            options={
                'ordering': ['-date_of_planting'],
            },
        ),
    ]
